const translation = {
  'А': 'a',
  'а': 'a',
  'Б': 'b',
  'б': 'b',
  'В': 'v',
  'в': 'v',
  'Г': 'h',
  'г': 'h',
  'Ґ': 'g',
  'ґ': 'g',
  'Д': 'd',
  'д': 'd',
  'Е': 'e',
  'е': 'e',
  'Є': 'ye',
  'є': 'ye',
  'Э': 'a',
  'э': 'a',
  'Ж': 'zh',
  'ж': 'zh',
  'З': 'z',
  'з': 'z',
  'И': 'y',
  'и': 'y',
  'І': 'i',
  'і': 'i',
  'Ї': 'yi',
  'ї': 'yi',
  'Й': 'i',
  'й': 'i',
  'К': 'k',
  'к': 'k',
  'Л': 'l',
  'л': 'l',
  'М': 'm',
  'м': 'm',
  'Н': 'n',
  'н': 'n',
  'О': 'o',
  'о': 'o',
  'П': 'p',
  'п': 'p',
  'Р': 'r',
  'р': 'r',
  'С': 's',
  'с': 's',
  'Т': 't',
  'т': 't',
  'У': 'u',
  'у': 'u',
  'Ф': 'f',
  'ф': 'f',
  'Х': 'kh',
  'х': 'kh',
  'Ц': 'ts',
  'ц': 'ts',
  'Ч': 'ch',
  'ч': 'ch',
  'Ш': 'sh',
  'ш': 'sh',
  'Щ': 'shch',
  'щ': 'shch',
  'Ь': 'ʹ',
  'ь': 'ʹ',
  'ы': 'i',
  'Ю': 'yu',
  'ю': 'yu',
  'Я': 'ya',
  'я': 'ya',
  '\'': '-',
  'ʹ': '-',
  '`': '-',
  ' ': '_',
  '()': '',
  '"': '_',
  '>': '_'
}

export function convertStringForAnchor (string) {
  // "()" is listed in the table above, but the table is applied one character
  // at a time, so a two-character key could never match and headings kept
  // their parentheses in the id. A link cannot carry them back: the anchor
  // expression stops at the first ")", so [x](page/p#Object.entries()) parses
  // as "…#Object.entries(" and lands nowhere. Dropping them here is what the
  // table meant to do, and it makes those links work as written.
  return string.trim().replaceAll('()', '').trim().split('')
    .map(char => translation[char] || char)
    .join('')
    .replaceAll('|', '_')
    .replaceAll('&lt;', '')
}
