const simple = [
  'warning',
  'coffee',
  'link',
  'no-entry',
  'link-ico',
  'link-dark',
  'link-grey',
  'pencil',
  'pen',
  'page_facing_up',
  'memo',
  'file_folder',
  'open_file_folder',
  'wink',
  'briefcase',
  'study',
  'search',
  'art',
  'sand-watch',
  'green-ok',
  'pushpin',
  'envelope',
  'book',
  'books',
  'lock',
  'unlock',
  'key',
  'trophy',
  'exclamation',
  'ambulance',
  'speech_balloon',
  'star',
  'arrow-right',
  'db',
  'node',
  'npm',
  'bash',
  'youtube',
  'debug-button',
  'debug-paused',
  'reload',
  'octocat',
  'git',
  'github',
  'atom',
  'sublime',
  'question'
]

const simpleFiles = simple.reduce((res, name) => Object.assign(res, { [name]: `${name}.png` }), {})

export const iconFiles = Object.assign(simpleFiles, {
  'open-in-new': 'open-in-new.svg',
  house: 'home-icon.svg',
  home: 'home-icon.svg',
  menu: 'table-of-contents-white.svg',
  warn: 'warning.png',
  cap: 'coffee.png',
  error: 'no_entry.png',
  'page-next': 'page-next.svg',
  'page-previous': 'page-previous.svg',
  paper: 'page_facing_up.png',
  file: 'memo.png',
  dir: 'open_file_folder.png',
  folder: 'open_file_folder.png',
  smile: 'wink.png',
  emotion: 'wink.png',
  hw: 'briefcase.png',
  mortar_board: 'study.png',
  require: 'point.png',
  point_up: 'point.png',
  good: 'ok-hand.png',
  ok_hand: 'ok-hand.png',
  exelent: 'good-hand.png',
  thumbsup: 'good-hand.png',
  mag: 'search.png',
  palette: 'art.png',
  hourglass: 'sand-watch.png',
  white_check_mark: 'green-ok.png',
  pin: 'pushpin.png',
  mail: 'envelope.png',
  yes: 'exclamation.png',
  speach: 'speech_balloon.png',
  negation: 'not.png',
  'git-ver': 'git.png',
  curl: 'curl.svg',
  'slider-button': 'slider-5.gif',
  'slider-button:hover': 'slider-2.gif',
  'draw-io': 'draw-io.svg'
})
