export const liveDemoColors = {
  var: '#a5f',
  equal: '#ddd',
  function: '#a5f',
  typeof: '#a5f',
  name: '#9bf',
  number: '#afa',
  numberOut: '#97d',
  string: '#fa5',
  stringOut: '#0ff',
  boolean: '#afa',
  booleanOut: '#b0d',
  operator: '#a5f',
  undefined: '#777',
  default: '#bbb',
  func_symbol: '#f84',
  func_body: '#eee',
  default: '#eee',
  console_func: '#fd0'
}
